WebBanHangOnline/WebBanHangOnline/Models/EF/ShippingFee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebBanHangOnline.Models.EF
{
    [Table("tb_ShippingFee")]
    public class ShippingFee
    {
        [Key]
        public int Id { get; set; }
        public decimal Value { get; set; }
    }
}

WebBanHangOnline/WebBanHangOnline/Areas/Admin/Controllers/ShippingFeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHangOnline.Models;
using WebBanHangOnline.Models.Common;
using WebBanHangOnline.Models.EF;

namespace WebBanHangOnline.Areas.Admin.Controllers
{
    public class ShippingFeeController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();

        // GET: Admin/ShippingFee
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult UpdateShippingFee()
        {
            // Kiểm tra xem có đối tượng ShippingFee nào có giá trị không
            var shippingFee = db.ShippingFees.FirstOrDefault();

            if (shippingFee != null)
            {
                // Đã có giá trị, điều hướng tới trang Edit
                return RedirectToAction("Edit", new { id = shippingFee.Id });
            }
            else
            {
                // Chưa có giá trị, điều hướng tới trang Add
                return RedirectToAction("Add");
            }
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(ShippingFee model)
        {
            if (ModelState.IsValid)
            {
                if(model.Value >= 0)
                {
                    db.ShippingFees.Add(model);
                    db.SaveChanges();
                    return RedirectToAction("Index", "Home");   
                }
                else
                {
                    ViewBag.KhongDuocNhapSoAm = "Không được nhập số âm";
                }
            }
            return View();
        }

        public ActionResult Edit(int id)
        {
            var shippingFee = db.ShippingFees.FirstOrDefault(sf => sf.Id == id);

            if (shippingFee != null)
            {
                return View(shippingFee);
            }
            return RedirectToAction("Index","Home");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ShippingFee model)
        {
            if (ModelState.IsValid)
            {
                if (model.Value >= 0)
                {
                    db.ShippingFees.Attach(model);
                    db.Entry(model).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index","Home");
                }
                else
                {
                    ViewBag.KhongDuocNhapSoAm = "Không được nhập số âm";
                }
            }
            return View(model);
        }
    }
}

WebBanHangOnline/WebBanHangOnline/Areas/Admin/Views/ShippingFee/Add.cshtml
@model WebBanHangOnline.Models.EF.ShippingFee

@{
    ViewBag.Title = "Thêm Phí vận chuyển";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section naviheader {
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/home" class="nav-link">Trang chủ</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">@ViewBag.Title</a>
        </li>
    </ul>
}


<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>@ViewBag.Title</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/admin/home">Trang chủ</a></li>
                    <li class="breadcrumb-item active">@ViewBag.Title</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">@ViewBag.Title</h3>

            <div class="card-tools">

                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                    <i class="fas fa-minus"></i>
                </button>

            </div>
        </div>

        <div class="card-body">

            <div class="bs-stepper-content">

                @using (Html.BeginForm("Add", "ShippingFee", FormMethod.Post, new { }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)
                    <!-- your steps content here -->
                    <div id="logins-part" class="content" role="tabpanel" aria-labelledby="logins-part-trigger">

                        <div class="form-group">
                            <label for="exampleInputPassword1">Phí vận chuyển</label>
                            @Html.HiddenFor(x => x.Value, new { @id = "PriceShip", @class = "form-control", @placeholder = "Nhập giá", @required = "true" })
                            <input id="textValue" class="form-control" type="text" placeholder="Nhập giá" required />
                            @Html.ValidationMessageFor(x => x.Value, null, new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            <a href="/admin/home" class="btn btn-danger">Quay lại</a>
                            <button type="submit" class="btn btn-primary">Xác nhận</button>
                        </div>
                    </div>

                }

            </div>

        </div>
        <!-- /.card-body -->
        <div class="card-footer">

        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->


@section scripts {
    <script>
     // Hàm để định dạng số thành chuỗi với dấu phẩy ngăn cách hàng nghìn
     function myFormatNumber(num) {
         return new Intl.NumberFormat('vi-VN').format(num);
     }

     // edit text price
        let hiddenForValue = document.querySelector("#PriceShip");
     let textPrice = document.getElementById("textValue");

     textPrice.value = myFormatNumber(parseFloat(0)) + " đ";
     textPrice.oninput = (e) => {
         let textPriceValue = parseFloat(textPrice.value.replaceAll('.', '').replace(" đ", ""));
         if (!isNaN(textPriceValue)) {
             // gán vào hiddenForValue
             hiddenForValue.value = textPriceValue;
             console.log(hiddenForValue.value);

             let textFormat = myFormatNumber(textPriceValue) + " đ";
             textPrice.value = textFormat;
         } else {
             textPrice.value = ''; // Đặt giá trị là rỗng nếu không thể chuyển đổi thành số
         }
     }
    </script>
}

WebBanHangOnline/WebBanHangOnline/Areas/Admin/Views/ShippingFee/Edit.cshtml
@model WebBanHangOnline.Models.EF.ShippingFee
@using WebBanHangOnline.Models.Common

@{
    ViewBag.Title = "Cập nhật Phí vận chuyển";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section naviheader {
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/home" class="nav-link">Trang chủ</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">@ViewBag.Title</a>
        </li>
    </ul>
}


<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>@ViewBag.Title</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/admin/home">Trang chủ</a></li>
                    <li class="breadcrumb-item active">@ViewBag.Title</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">@ViewBag.Title</h3>

            <div class="card-tools">

                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                    <i class="fas fa-minus"></i>
                </button>

            </div>
        </div>
        <div class="card-body">
            @if (!string.IsNullOrEmpty(ViewBag.KhongDuocNhapSoAm))
            {
                <div class="alert alert-danger">
                    @ViewBag.KhongDuocNhapSoAm
                </div>
            }
            @if (Model != null)
            {
                <div class="bs-stepper-content">

                    @using (Html.BeginForm("Edit", "ShippingFee", FormMethod.Post, new { }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true)
                        @Html.HiddenFor(x => x.Id)
                        <!-- your steps content here -->
                    <div id="logins-part" class="content" role="tabpanel" aria-labelledby="logins-part-trigger">

                        <div class="form-group">
                            <label for="exampleInputPassword1">Phí vận chuyển hiện tại</label>
                            <input class="form-control" value="@Common.FormatNumber(Model.Value,2) đ" readonly="readonly" />
                        </div>

                        <div class="form-group">
                            <label for="exampleInputPassword1">Phí vận chuyển mới</label>
                            @Html.HiddenFor(x => x.Value, new { @id = "PriceShip", @class = "form-control", @placeholder = "Nhập giá", @required = "true" })
                            <input id="textValue" class="form-control" type="text" placeholder="Nhập giá" required />
                            @Html.ValidationMessageFor(x => x.Value, null, new { @class = "text-danger" })
                        </div>


                        <div class="form-group">
                            <a href="/admin/home" class="btn btn-danger">Quay lại</a>
                            <button type="submit" class="btn btn-primary">Xác nhận</button>
                        </div>
                    </div>

                    }
                </div>
            }

        </div>
        <!-- /.card-body -->
        <div class="card-footer">

        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->

@section scripts {
    <script>
     // Hàm để định dạng số thành chuỗi với dấu phẩy ngăn cách hàng nghìn
     function myFormatNumber(num) {
         return new Intl.NumberFormat('vi-VN').format(num);
     }

     // edit text price
        let hiddenForValue = document.querySelector("#PriceShip");
     let textPrice = document.getElementById("textValue");

     textPrice.value = myFormatNumber(parseFloat(0)) + " đ";
     textPrice.oninput = (e) => {
         let textPriceValue = parseFloat(textPrice.value.replaceAll('.', '').replace(" đ", ""));
         if (!isNaN(textPriceValue)) {
             // gán vào hiddenForValue
             hiddenForValue.value = textPriceValue;
             console.log(hiddenForValue.value);

             let textFormat = myFormatNumber(textPriceValue) + " đ";
             textPrice.value = textFormat;
         } else {
             textPrice.value = ''; // Đặt giá trị là rỗng nếu không thể chuyển đổi thành số
         }
     }
    </script>
}